<a href="https://colab.research.google.com/github/chacha86/bigData1/blob/main/numpy%20%EC%82%AC%EC%9A%A9%EB%B2%952.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 배열의 연산
import numpy as np

np.random.seed(1)
arr1 = np.random.randint(-10, 10, (3,4))

# 기초 통계 연산
arr1.mean()
arr1.max()
arr1.min()
arr1.sum()

np.random.seed(100)
arr2 = np.random.randint(-10, 10, (3,4))

print(arr1)
print(arr2)

# 두 배열의 연산 - 사칙 연산
arr3 = arr1 + arr2
arr4 = arr1 - arr2
arr5 = arr1 * arr2
arr6 = arr1 / arr2
arr7 = arr1 % arr2


# 배열의 값을 절대값으로
arr2 = np.abs(arr2)

print(arr2)

# arr1원소의 값을  arr2 원소만큼 제곱
arr9 = arr1 ** arr2


# 배열의 원소의 제곱근
arr10 = np.sqrt(arr2)

print(arr1 * arr2)

# 행렬의 점곱(dot product)
# (2 X 3) . (3 X 4)
# 3 4 3 4
arr1.shape
arr2.shape

# 행렬의 모습을 바꾸고 싶다. - reshape(행렬의 모양)
arr2 = arr2.reshape([4,3])
np.dot(arr1, arr2)

# 두 행렬의 비교
arr1 == arr2
print(arr2.size)

# reshaep 배열의 모양을 바꿀 때 사용. 원소의 개수에 주의
arr2 = arr2.reshape([3, -1])
arr2.shape


# 각 배열의 원소 일치 여부
# 단, 배열의 shape가 다르면 False가 나옴
arr1 == arr2

# shape이 같은 두 배열을 == 비교하면 각 원소의 일치 여부
# 배열의 shape가 동일할 때 완전 일치하는지에 대한 여부
np.array_equal(arr1, arr2)



In [ ]:
# 1차원 배열 -> 벡터
arr3 = np.arange(1, 16)
arr3.size # 배열의 원소 개수
arr3.ndim

arr3 = arr3.reshape((3,-1))
arr3 = arr3.reshape((5, 3, -1))


In [ ]:
arr1 = np.arange(1, 12)

# 배열의 차원 확장 및 축소

# 확장 - 차원을 확장. axis = 0 은
arr2 = np.expand_dims(arr1, axis=0)
arr3 = np.expand_dims(arr1, axis=1)

# 축소
np.squeeze(arr2, axis=0)
np.squeeze(arr3, axis=1)




array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
# 정렬
import numpy as np
np.random.seed(1)
arr = np.random.randint(1, 100, 12)

#arr.sort() # 원본에 적용
arr2 = np.sort(arr) # 원본에 적용 X

arr3 = arr.reshape([3,4]) # 3 X 4 배열로 변환

# 1차원
np.sort(arr)# 오름차순, 

# 2차원 
# 세로로 정렬
arr=np.sort(arr3, axis=0) # 오름차순
print(arr) #세로로 오름차순 정렬된 배열임
arr[::-1] #거꾸로 하면 세로로 내림차순

# 가로로 정렬
arr2 = np.sort(arr3, axis=1) # 오름차순 
print(arr2) # 가로로 오름차순 정렬된 배열임
print(arr2[::-1]) # 거꾸로 탐색해도 어차피 정렬된 행단위로 뒤지기 때문에 내림차순은 할 수 없음.

# 가로로 내림차순 정렬하기
arr4 = np.sort(arr3.reshape(arr3.size))[::-1].reshape([3,4])

# 정렬된 원소들의 원래 인덱스 얻기

idx = arr.argsort()[::-1] # 내림차순 정렬된 원소들의 인덱스를 얻어서
arr[idx[:5]] # 앞에서 5개를 가져오면. 값이 큰 top5를 가져올 수 있다.



[[17  2 73 10]
 [38  6 77 65]
 [76 13 80 72]]
[[10 13 38 73]
 [ 6 65 76 80]
 [ 2 17 72 77]]
[[ 2 17 72 77]
 [ 6 65 76 80]
 [10 13 38 73]]


array([[10, 13, 38, 73],
       [ 6, 65, 76, 80],
       [ 2, 17, 72, 77]])

In [52]:
# 배열 붙이기, 나누기
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

print(arr1) 
print(arr2)


# 배열을 붙이고 떼는 건 2차원 배열부터 진행이 가능하다. 때문에 1차원 배열 2개를 붙이려면 먼저 2차원으로 차원 확장한다.
arr3 = np.expand_dims(arr1, axis=0) 
arr4 = np.expand_dims(arr2, axis=0)

arr5 = arr1.reshape(2,2)
arr6 = arr2.reshape(2,2)

# 1X4 배열 붙이기
np.concatenate((arr3, arr4), axis=0)
np.concatenate((arr3, arr4), axis=1)

# 2X2 배열 붙이기
np.concatenate((arr5, arr6), axis=0)
np.concatenate((arr5, arr6), axis=1)

arr7 = np.arange(1, 13)
arr8  =arr7.reshape(3,4) # 3 X 4 배열을 만든 후

print(np.split(arr8, 2, axis=1)) # 쪼개기. arr8은 쪼갤 대상, 2는 쪼개어져야 하는 수, axis=1은 쪼개는 방향이 세로.
print(np.split(arr8, 3, axis=0)) # 쪼개기. arr8은 쪼갤 대상, 3은 쪼개어져야 하는 수, axis=0은 쪼개는 방향이 가로.
# 쪼갤 때 주의할 점은 각 축의 원소의 개수가 쪼개려는 수로 나누어 떨어져야 함.
# ex) 행이 6개인 배열을 가로 방향으로 쪼개려면 6으로 나누어 떨어지는 1, 2, 3, 6으로만 쪼개어질 수 있음. 4개로는 쪼갤 수 없음.





[1 2 3 4]
[5 6 7 8]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])