<a href="https://colab.research.google.com/github/chacha86/python2-week-20220803/blob/main/numpy_example1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ndArray

import numpy as np

# 1차원 ndArray 생성
np.array([1,2,3,4])
arr1 = np.array((1,2,3,4)) # 넘파이 ndArray
arr2 = [1,2,3,4] # 파이썬 리스트
type(arr1)
type(arr2)


list

In [ ]:
# 2차원 ndArray
arr2 = np.array([[1,2,3,4], [5,6,7,8]])

# 3차원 ndArray
arr3 = np.array([[[1.0,2.0,3.0,4.0], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]]])

In [ ]:
# d
arr1.ndim
arr2.ndim
arr3.ndim

3

In [ ]:
# 배열의 형태
arr1.shape
arr2.shape
arr3.shape

# 배열의 사이즈
arr1.size
arr2.size
arr3.size

# 원소의 타입
arr1.dtype
arr2.dtype
arr3.dtype

dtype('float64')

In [ ]:
# 배열 생성 함수
# 0 행렬
np.zeros((3, 4))

# 1 행렬
np.ones((2, 3, 4))

# k 행렬
np.full((2, 2), 3)

# like 함수 - 다른 배열의 모양을 본따서 만들기
np.zeros_like(arr2)
np.ones_like(arr2)
np.full_like(arr2, 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [ ]:
# random -> 난수 발생
np.random.seed(10) # 난수를 최초로 한번만 생성
np.random.randint(-100, 100, (2, 3)) # -100 ~ 100 사이의 숫자로 2 X 3 행렬 생성

np.random.randint(0, 10, (2, 2, 3)) # -100 ~ 100 사이의 숫자로 2 X 3 행렬 생성

array([[[9, 0, 1],
        [8, 9, 0]],

       [[8, 6, 4],
        [3, 0, 4]]])

In [ ]:
# 리스트 인덱싱
li = [1,2,3,4]
li[0]

# 1차원 배열 인덱싱
arr1[0] # 하나만 접근
arr1[::] # 슬라이싱

# 2차원 배열 인덱싱
arr2[0, 1] # 행과 열 두개의 축정보 필요.
arr2[1, 2]

arr2[1:2:, 1:3:] # 슬라이싱

# fancy 인덱싱 -> 원하는 인덱스를 배열로 넘기는 것.
# 1차원 
arr1[[0, 1, 3]]

# 2차원
arr2[[0, 1], [1, 2]]
arr2[::, [0, 3]]

# 논리값 인덱싱 - True인 것만
arr1[[True, False, True, False]]
arr1[arr1 > 2]


array([3, 4])