<a href="https://colab.research.google.com/github/chacha86/bigData1/blob/main/%EB%84%98%ED%8C%8C%EC%9D%B4%20%EC%82%AC%EC%9A%A9%EB%B2%951.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np

li = [1,2,3,4,5] # 일반 파이썬 리스트. 연산 속도가 느리고 기능의 제약이 많다.

type(li) # li 의 타입 체크. List 타입으로 나온다.

arr = np.array([1,2,3,4,5]) # ndArray. numpy 수치연산용 배열. 고속의 연산속도와 다양한 연산 기능을 제공. 유수한 라이브러리들이 채용하여 사용중.
type(arr) # arr의 타입 체크. ndArray 타입으로 나온다.

li = [7,8,9,10]
tupl = (5,6,7,8)
arr2 = np.array(li) # 리스트를 이용해 ndArray 만들기
arr3 = np.array(tupl) # 튜플을 이용해 ndArray 만들기

arr3

# 2차원 배열 만들기
arr4 = np.array([[1,2,3,4],
                 [5,6,7,8]])

# 3차원 배열 만들기

arr5 = np.array([[[1,2,3,4],
                 [5,6,7,8]],
                [[1,2,3,4],
                 [5,6,7,8]] ])

# 배열의 모양 확인
arr3.shape

arr4.shape

arr5.shape


# 배열의 차원 확인
arr3.ndim
arr4.ndim
arr5.ndim


# 배열의 원소 개수 확인
arr3.size
arr4.size
arr5.size

16

In [145]:
# 인덱싱

# 1차원 배열 인덱싱
arr3[0]
# 1차원 배열 슬라이싱
arr3[1 : 4 : 2]


# 2차원 배열 인덱싱
arr4[0, 2]
arr4[1, 3]

arr5 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

# 2차원 배열 슬라이싱. 2차원의 경우 슬라이싱을 행과 열 두 축에 대해서 고려해야 한다.
# 아래는 행은 모두 출력하고 열은 0,1열만 출력하는 코드
arr4[:, :2]




# arr5를 아래와 같이 2차원 배열 슬라이싱 하기
'''
[6,7]
[10,11]
'''
arr5[1:3, 1:3]
'''
[1,3]
[5,7]
[9,11]
[13,15]
'''
arr5[:, 0:3:2]


# fancy 인덱싱 - 인덱스를 여러개 선택
arr6 = np.array([1,2,3,4,5,6,7,8,9,10])

arr6[[2, 5, 9]] # 2, 5, 9 세개의 인덱스를 사용. 이때 인덱스로 사용된 2,5,9가 배열 형태임의 유의



# arr5를 fancy 인덱싱을 이용해 아래와 같이 출력하기
'''
[1,3]
[5,7]
[13,15]
'''
print(arr5[[0,1,3], 0:3:2])


# 논리값(bool) 인덱싱
arr7 = np.array([[1,2],
                 [3,4]])

arr8 = np.array([[True, False],
                 [False, True]])

# arr8의 True위치에 있는 arr7의 원소만 선택
arr7[arr8]


arr9 = np.array([1,2,3,4,5])
arr10 = np.array([True, False, True, False, True])

arr9[arr10] # arr10의 True 위치에 있는 값만 arr9에서 가져옴.

arr8[arr8 > 3] # 이를 응용하면 arr8 > 3으로 조건식에 만족하는 원소만 가져올 수 있음


[[ 1  3]
 [ 5  7]
 [13 15]]


array([4, 5])

In [113]:
# 수열로 1차원 배열 만들기
arr = np.arange(10, 21, 2)

# 랜덤하게 숫자 뽑아주는것. 순서대로 최소값, 최대값, 배열의 형태
arr2 = np.random.randint(-10, 10, (2,3,4)) # -10 ~ 10까지의 임의의 정수를 뽑아 2 X 3 X 4 배열을 만듦.


# 배열생성 삼총사
arr3 = np.zeros([3, 3,4]) # 영행렬
arr4 = np.ones([3,4]) # 1로 채움
arr5 = np.full([3,4], 4) # 특정 숫자로 채움

# arr2와 같은 형태로 0행렬 만듦
arr6 = np.zeros_like(arr2)



array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [141]:
# 랜덤 시드. 시드를 주면 무작위값을 항상 일정하게 뽑을 수 있음.
np.random.seed(1)
arr1 = np.random.randint(-100, 100, (3,4))

print(arr1)

np.random.seed(100)
arr2 = np.random.randint(-100, 100, (3,4))

print(arr2)

np.random.seed(5)
arr3 = np.random.randint(-10, 10, 5)

print(arr3)


# 행렬 연산 - 원소끼리 연산
#최대
arr1.max()
arr2.max()
arr3.max()

# 최소
arr1.min(axis=0) # axis 0은 세로. 인덱스가 행 기준으로 움직임
arr1.min(axis=1) # axis 1은 가로. 인덱스가 열 기준으로 움직임

# 합
arr1.sum()
arr1.sum(axis=0)
arr1.sum(axis=1)

# 평균
arr1.mean()
arr1.mean(axis=0)
arr1.mean(axis=1)

[[-63  40 -28  37]
 [ 33 -21  92  44]
 [ 29 -29  34 -75]]
[[-92 -76 -33   3]
 [-13 -21  76  38]
 [ -6  80  -2 -47]]
[-7  4  5 -4  6]


array([ -3.5 ,  37.  , -10.25])